# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'TinyQRScanner_Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QRScanner_Sample
  pod 'TinyQRScanner', :path => '../'
end
